### ISSUE TITLE
twitchIO race condition?

### ISSUE THREAD

**Issue by PotatoesMakeChips** [PotatoesMakeChips/ZuluAlpha-TwitchBot#1]
See Line 25 of ZuluAlphaPotato.py

Runs correctly some of the time but occasionally shows
```
Traceback (most recent call last):
  File "/home/potatoesmkchips/.local/share/virtualenvs/ZuluAlphaPotato-TwitchBot-XoW3xk5E/lib/python3.9/site-packages/twitchio/client.py", line 193, in wrapped
    await func(*args)
  File "/mnt/d/Documents/github/ZuluAlphaPotato-TwitchBot/ZuluAlphaPotato.py", line 25, in event_ready
    loop.create_task(channelObj.send("/me has arived"))
AttributeError: 'NoneType' object has no attribute 'send'
```
Line 22 (bellow),
```
channelObj = self.get_channel(os.environ['CHANNEL'])
```
can be printed out as None when the error occurs leading me to think that  `self.get_channel` could be running before the parent class has finished initialising???

**Comment by PotatoesMakeChips** [comment]
instead of creating a new loop (line 24) find way to interface into twitchio one?? 
```
loop = asyncio.get_event_loop()
```
